# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class AggregationType(object):
    FedAvg = 0
    FedProx = 1
    Scaffold = 2
    FedNova = 3
    qffl = 4
    FedCM = 5

