# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class AggregationType(object):
    FedAvg = 0
    FedProx = 1
    FedAdagrag = 2
    FedMeta = 3
    qffl = 4

