# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DPParams(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DPParams()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDPParams(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DPParams
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DPParams
    def DpEps(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DPParams
    def DpDelta(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # DPParams
    def DpNormClip(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(3)
def DPParamsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddDpEps(builder, dpEps): builder.PrependFloat32Slot(0, dpEps, 0.0)
def DPParamsAddDpEps(builder, dpEps):
    """This method is deprecated. Please switch to AddDpEps."""
    return AddDpEps(builder, dpEps)
def AddDpDelta(builder, dpDelta): builder.PrependFloat32Slot(1, dpDelta, 0.0)
def DPParamsAddDpDelta(builder, dpDelta):
    """This method is deprecated. Please switch to AddDpDelta."""
    return AddDpDelta(builder, dpDelta)
def AddDpNormClip(builder, dpNormClip): builder.PrependFloat32Slot(2, dpNormClip, 0.0)
def DPParamsAddDpNormClip(builder, dpNormClip):
    """This method is deprecated. Please switch to AddDpNormClip."""
    return AddDpNormClip(builder, dpNormClip)
def End(builder): return builder.EndObject()
def DPParamsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)