# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EarlyStop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EarlyStop()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEarlyStop(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EarlyStopBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x46\x4C\x4A\x30", size_prefixed=size_prefixed)

    # EarlyStop
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EarlyStop
    def EarlyStopType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # EarlyStop
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # EarlyStop
    def Rounds(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(3)
def EarlyStopStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddEarlyStopType(builder, earlyStopType): builder.PrependInt8Slot(0, earlyStopType, 0)
def EarlyStopAddEarlyStopType(builder, earlyStopType):
    """This method is deprecated. Please switch to AddEarlyStopType."""
    return AddEarlyStopType(builder, earlyStopType)
def AddWeight(builder, weight): builder.PrependFloat32Slot(1, weight, 0.0)
def EarlyStopAddWeight(builder, weight):
    """This method is deprecated. Please switch to AddWeight."""
    return AddWeight(builder, weight)
def AddRounds(builder, rounds): builder.PrependInt32Slot(2, rounds, 0)
def EarlyStopAddRounds(builder, rounds):
    """This method is deprecated. Please switch to AddRounds."""
    return AddRounds(builder, rounds)
def End(builder): return builder.EndObject()
def EarlyStopEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)