# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class Metrics(object):
    accuracy = 0
    precision = 1
    recall = 2
    AUC = 3
    f1 = 4
    fbeta = 5

