# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers

class RequestGetResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsRequestGetResult(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestGetResult()
        x.Init(buf, n + offset)
        return x

    # RequestGetResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestGetResult
    def FlName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RequestGetResult
    def Iteration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RequestGetResult
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RequestGetResultStart(builder): builder.StartObject(3)
def RequestGetResultAddFlName(builder, flName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(flName), 0)
def RequestGetResultAddIteration(builder, iteration): builder.PrependInt32Slot(1, iteration, 0)
def RequestGetResultAddTimestamp(builder, timestamp): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)
def RequestGetResultEnd(builder): return builder.EndObject()
