# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestPushMetrics(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestPushMetrics()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestPushMetrics(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RequestPushMetricsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x46\x4C\x4A\x30", size_prefixed=size_prefixed)

    # RequestPushMetrics
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestPushMetrics
    def Loss(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RequestPushMetrics
    def Accuracy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(2)
def RequestPushMetricsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddLoss(builder, loss): builder.PrependFloat32Slot(0, loss, 0.0)
def RequestPushMetricsAddLoss(builder, loss):
    """This method is deprecated. Please switch to AddLoss."""
    return AddLoss(builder, loss)
def AddAccuracy(builder, accuracy): builder.PrependFloat32Slot(1, accuracy, 0.0)
def RequestPushMetricsAddAccuracy(builder, accuracy):
    """This method is deprecated. Please switch to AddAccuracy."""
    return AddAccuracy(builder, accuracy)
def End(builder): return builder.EndObject()
def RequestPushMetricsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)