# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestPullWeight(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestPullWeight()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestPullWeight(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RequestPullWeightBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x46\x4C\x4A\x30", size_prefixed=size_prefixed)

    # RequestPullWeight
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestPullWeight
    def Iteration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RequestPullWeight
    def WeightNames(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RequestPullWeight
    def WeightNamesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RequestPullWeight
    def WeightNamesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def Start(builder): builder.StartObject(2)
def RequestPullWeightStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddIteration(builder, iteration): builder.PrependInt32Slot(0, iteration, 0)
def RequestPullWeightAddIteration(builder, iteration):
    """This method is deprecated. Please switch to AddIteration."""
    return AddIteration(builder, iteration)
def AddWeightNames(builder, weightNames): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(weightNames), 0)
def RequestPullWeightAddWeightNames(builder, weightNames):
    """This method is deprecated. Please switch to AddWeightNames."""
    return AddWeightNames(builder, weightNames)
def StartWeightNamesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def RequestPullWeightStartWeightNamesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartWeightNamesVector(builder, numElems)
def End(builder): return builder.EndObject()
def RequestPullWeightEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)