# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

class ResponseCode(object):
    SUCCEED = 200
    SucNotReady = 201
    OutOfTime = 300
    RequestError = 400
    SystemError = 500

