# automatically generated by the FlatBuffers compiler, do not modify

# namespace: schema

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UnsupervisedEvalItems(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnsupervisedEvalItems()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnsupervisedEvalItems(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UnsupervisedEvalItemsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x46\x4C\x4A\x30", size_prefixed=size_prefixed)

    # UnsupervisedEvalItems
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnsupervisedEvalItems
    def EvalItems(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from mindspore_fl.schema.UnsupervisedEvalItem import UnsupervisedEvalItem
            obj = UnsupervisedEvalItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UnsupervisedEvalItems
    def EvalItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UnsupervisedEvalItems
    def EvalItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def UnsupervisedEvalItemsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddEvalItems(builder, evalItems): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(evalItems), 0)
def UnsupervisedEvalItemsAddEvalItems(builder, evalItems):
    """This method is deprecated. Please switch to AddEvalItems."""
    return AddEvalItems(builder, evalItems)
def StartEvalItemsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def UnsupervisedEvalItemsStartEvalItemsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartEvalItemsVector(builder, numElems)
def End(builder): return builder.EndObject()
def UnsupervisedEvalItemsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)
